name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.0', '8.1', '8.2', '8.3']
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Setup Packages
        run: composer update -o
      - name: Run Analyse
        run: |
          composer analyse src
      - name: Run Test Cases
        run: |
          composer test